### PR TITLE
DCD-1476 Migrating AWS Classic LoadBalancer to ALB/NLB

### PR DESCRIPTION
**Pull request by grimmyson**
DCD-1476 Migrating AWS Classic LoadBalancer to ALB/NLB

### CODE REVIEW

**Comment by grimmyson** [comment]
CI build - https://server-syd-bamboo.internal.atlassian.com/browse/ZDCD-AWSBITBUCKET57-28

**Comment by grimmyson** [comment]
CI build - https://server-syd-bamboo.internal.atlassian.com/browse/ZDCD-AWSBITBUCKET57-33

**Comment by errcode1202** [comment]
@grimmyson something to consider is how this change may affect existing clients that will have deployed using the QS's prior to this change. They will be using the classic load balancer, once this PR is merged if they update their stack this change may be [forced onto them](https://hello.atlassian.net/wiki/spaces/DCD/pages/731049246/Approach#The-key-issue) resulting in an unexpected/broken stack. 

To be sure, it might be worth being a backward compatibility test:
1. Deploy using current QS's
2. Perform stack update but point the update to these updated templates. 
3. Observe update behaviour.

**Review by errcode1202 — CHANGES_REQUESTED** [review]
@grimmyson something to consider is how this change may affect existing clients that will have deployed using the QS's prior to this change. Current clients will be using the classic load balancer, once this PR is merged if these clients then update their stack this change may be [forced onto them](https://hello.atlassian.net/wiki/spaces/DCD/pages/731049246/Approach#The-key-issue) resulting in an unexpected/broken stack. 

To be sure, it might be worth performing a backward compatibility test:
1. Deploy using current QS's
2. Perform stack update but point the update to these modified templates. 
3. Observe update behaviour for anything abnormal.

Let me know what you think. This might not be necessary?

**Pull request closed without merging**
